name: mysql-schema-diff
author: Sean Burke
description: Check to see if the MySQL schemas for 2 DBs are the same
branding:
  icon: 'database'
  color: 'purple'
inputs:
  hostname:
    description: 'The host of the first mysql connection'
    required: false
    default: 'localhost'
  username:
    description: 'The username of the first mysql connection'
    required: true
  password:
    description: 'The password of the first mysql connection'
    required: false
    default: ''
  database:
    description: 'The database name of the first mysql connection'
    required: true
  file: 
    description: 'The name of the first SQL Dump file'
    default: 'db.sql'
    required: true
runs:
  using: "composite"
  steps:
    - name: MySQL Diff
      shell: bash
      run: |
        user=${{ inputs.username }};
        host=${{ inputs.hostname }};
        pwd=${{ inputs.password }};
        db=${{ inputs.database }};
        echo "Connecting to DB"
        mysqldump --defaults-extra-file=<(printf '[client]\nuser = %s\npassword = %s\nhost = %s' $user $pwd $host) -d --skip-add-drop-table --skip-add-drop-database --single-transaction $db | sed -e 's/AUTO_INCREMENT=[[:digit:]]* //' | sed -e 's/Host: .*  //' | sed -e 's/-- Dump completed on .*//' > ${{ inputs.file }}
        if [[ $? -ne 0 ]]; then
            echo >&2 "SQL error"
            exit 1
        fi
        echo "${{ inputs.file }} created"
        echo "Completed"

  
